server:
  port: 8012
spring:
  application:
    name: weather-data-server
  redis:
    host: 192.168.1.245
    port: 6379
    database: 0
feign:
  client:
    config:
      feignName:
        connect-timeout: 5000
        read-timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka